### ISSUE TITLE
Unable to use the .so file

### ISSUE THREAD

**Issue by thorion21** [SoftwareGuy/ENet-CSharp#14]
Hi,
The library from nxrighthere didn't work for me so I tried to use yours. I tried to build the .so library but I cannot wrap my head around of how to use it with RiderC#. Adding a reference seemed not to work because Rider doesn't find the file.

Maybe you have an idea, my problem appeared after a couple thousands of packets were sent between clients and the server and at a random moment in time, my program crashed and "free(): invalid pointer Aborted (core dumped)" showed up. Maybe you have an idea...

Thank you for your time :)

**Comment by SoftwareGuy** [comment]
That's definitely not good. Sounds like memory corruption, or a pointer got corrupted or turned into a NULL crashing ENET.

Was this on bare metal or was it inside a container/virtual machine? Is it possible you can give me a reproduction project? If not, I can make one myself.

As for building, you can use MSBuild (you'll need to grab the Dotnet 2.x LTS/3.x SDK) and it'll spit out a library.

**Comment by SoftwareGuy** [comment]
Any updates to this, @thorion21 ? I can't debug any further unless you give me more information.

**Comment by ghost** [comment]
@thorion21 You could get already build libraries from https://github.com/SoftwareGuy/Ignorance/ to check if you are doing something wrong while building the library. I'm already using them without any problems.

@SoftwareGuy Do you build linux libraries as static or shared? They are working on Ubuntu but I'm not able to use them on Alpine Linux.

**Comment by SoftwareGuy** [comment]
Going to close this. And for the record, @muratGG, on Linux they are built with Ubuntu GNU C compiler, so probably GNU C libraries. Alphine I think uses musl or uclibc (some very minimal version of C libraries) so you'd most likely need to recompile for it.
