### ISSUE TITLE
iOS Debugging - File Access Permission

### ISSUE THREAD

**Issue by ghost** [SoftwareGuy/ENet-CSharp#15]
Hello,

I'm trying to use the debug version of your library for iOS but it is trying to create a log file and write to that file.

But it is not possible as iOS application only has access to certain folders because of security.

Here is the log event I got from the device.
Sandbox: backgammon(400) deny(1) file-write-create /enet_log.txt

Could you guide me how to use the debug version for iOS?

P.S. Thanks for the the great work.

**Comment by SoftwareGuy** [comment]
It's trying to write the log file to the root directory on the iPhone? Wow, that's weird.

I'll make a fix for the logger on iOS to only use printf, because looks like that's the only option we have available, unless I refactor the logger.

**Comment by ghost** [comment]
I think printf will be fair, at least we will able to check logs from XCode.

Thanks.

**Comment by SoftwareGuy** [comment]
Alright, this should now be fixed. Please check and get back to me ASAP.

Printed logs appear from my iPad 2 in the Xcode output window. No more errors about denying file writes in Console.app . 😌

**Comment by ghost** [comment]
I was using build libraries from Ignorance as this repo doesn't have any releases. #16 

I will try when they are updated as I don't have much experience on building from source.

**Comment by SoftwareGuy** [comment]
Ahh sorry mate. My bad. Lemme get you some freshly baked ones.

**Comment by SoftwareGuy** [comment]
Here's the iOS libraries. Rename the one you want to use to the `libenet.a` filename.

[libenet-iOS-Combo.zip](https://github.com/SoftwareGuy/ENet-CSharp/files/4774245/libenet-iOS-Combo.zip)

**Comment by ghost** [comment]
Thank you.
