### ISSUE TITLE
CI and Binary Releases

### ISSUE THREAD

**Issue by ghost** [SoftwareGuy/ENet-CSharp#16]
Is it possible to configure CI with Github Actions and release binaries for this repo?

Currently I'm using the binaries from Ignorance but I think they should be released from this repo.

**Comment by SoftwareGuy** [comment]
Currently a work in progress - I'm still trying to figure out how to pipeline it. Right now GitHub does auto-build every commit. I suppose I can make it release the binaries every time it runs.

I'll leave this open for feedback as I implement it.

**Comment by SoftwareGuy** [comment]
So far so good - got Linux builds working. Working on Apple iOS building now using Xcode. 

Next step is to automatically making releases and then every commit will produce a new up-to-date release.

**Comment by SoftwareGuy** [comment]
Got Apple iOS builds automatically popping out of GitHub actions. Now I'll just need to have them automatically create releases and we are good to go (at least for Linux and iOS).

**Comment by SoftwareGuy** [comment]
Autobuilds are working beautifully. Can you give them a shot?

**Comment by ghost** [comment]
Looks great, thank you. I will try them as soon as possible.

Will you also work on other operating systems like Android, Mac and Windows releases?
We are using this library with Unity so we need builds for all operating systems.

**Comment by SoftwareGuy** [comment]
I do work with Windows, Mac and Android as well. I can probably have the build system build them too, I'd just need to define it as a build job. I intend to do this as soon as IRL work gives me a bit of a break.

**Comment by ghost** [comment]
I tried iOS version today and it is working fine. Thank you.

**Comment by SoftwareGuy** [comment]
Perfect - will close this. Let me know if they break or anything.
