### ISSUE TITLE
NSLog instead of printf for iOS

### ISSUE THREAD

**Issue by ghost** [SoftwareGuy/ENet-CSharp#18]
Thanks for fixing the logging issue on iOS with #15 task.

You are currently using printf for logging but it is only available while debugging.

If you could use [NSLog](https://developer.apple.com/documentation/foundation/1395275-nslog) then it will be possible to check logs even from TestFlight releases.

I don't know much about how building native code works.

Is it possible to use NSLog for iOS build maybe even for MacOS builds?

Thanks.

**Comment by SoftwareGuy** [comment]
Hmm, I'll have to look into this - is NSLog available from native C world on Apple?

Not going to lie but this is an interesting proposal. Does NSLog log items also show up in "Console" on Mac when you've got a iOS device plugged in and watching the logs from there?

**Comment by ghost** [comment]
I don't know how native world really works :)

[It seems you are able to use it, there are some ideas here.](https://stackoverflow.com/questions/8372484/nslog-style-debug-messages-from-c-code)

Yes you could track your iOS device logs with console app on MacOS.

<img width="339" alt="Screen Shot 2020-06-19 at 10 24 35" src="https://user-images.githubusercontent.com/51789354/85107741-243a1680-b217-11ea-97e9-f824383393aa.png">

It will also be very helpful for debugging issues while apple is reviewing your application for apple store.

**Comment by SoftwareGuy** [comment]
Currently working on this one, I think I might have a winner, but I'm getting a compile error right now. Should be very close though...

**Comment by SoftwareGuy** [comment]
Alright, so trying to mix in NSLog in gives lots of errors, but apparently `asl_log` seems to be deprecated but works...?

I think I need to clean the caches on my MacBook Pro as Xcode complains about non-existant things about `enet_mem_acquire` and `enet_mem_release` that are nowhere to be seen. Might try my Hackintosh instead.

**Comment by ghost** [comment]
https://developer.apple.com/documentation/os/os_log

This one seems to be the replacement for asl_log but it has higher os version dependency like iOS 10.0+ and macOS 10.12+

**Comment by SoftwareGuy** [comment]
Closing due to age of issue.
