### ISSUE TITLE
use enet native part inside c++ server

### ISSUE THREAD

**Issue by Kemoke** [SoftwareGuy/ENet-CSharp#19]
Is there some way to use the modified enet lib inside c++ server?

**Comment by SoftwareGuy** [comment]
Yes, you should be able to. I haven't worked too deeply with C++ but you can do one of the following:

1. Include the native files in your C++ project. This would allow you to bake Enet into your application's library or executable directly. You could also trim the fat and stub logging functions you may not need, etc. Probably the easiest way, and then add compile defintions to include debug support in ENet native, etc. Enet native will compile on the Microsoft Visual C++ Compiler and GCC, as well as Clang from Apple.

2. Use the native DLL and use `extern` calls (I believe that's what they are called?) to the DLL.

**Comment by Kemoke** [comment]
I managed to get it working. I was building the wrong project for the native lib.
