### ISSUE TITLE
C# Server with C++ Client

### ISSUE THREAD

**Issue by StuBedore** [SoftwareGuy/ENet-CSharp#20]
Hi,

I am trying to get ENet working with a C# server and a C++ client. 

My issue is that the client says the connection was successful, however the server's EventType.Connect event is never called.

Is there any known issues with this?

Thanks.

**Comment by StuBedore** [comment]
Nevermind, I solved it.

It was due to packet buffering. flushing the client on a successful connection solved it.

**Comment by SoftwareGuy** [comment]
Glad you got it resolved. Be careful with excessive flushing though.
