### ISSUE TITLE
Unity build?

### ISSUE THREAD

**Issue by ttay24** [SoftwareGuy/ENet-CSharp#21]
Hi, I didn't see any issues about this, so figured I would ask. The nxrighthere repo has a separate build for Unity. Is there supposed to be a build artifact for Unity projects on here, or what's the difference when building for Unity?

**Comment by SoftwareGuy** [comment]
If you want to use ENet-C# in Unity, all you need to do is drop in the `ENet.cs` file from this repo, slap in the desired ENet runtime native blobs and off you go. NX's repo just has this automated which is a nice little touch. I might look into a mechanism later on, but it's simply a matter of copying the native libs to your project's Plugins folder and dragging in `ENet.cs` somewhere.

**Comment by SoftwareGuy** [comment]
Closing since this is getting dusty - reopen if required.
