### ISSUE TITLE
Auto reconnect

### ISSUE THREAD

**Issue by ErcinDedeoglu** [SoftwareGuy/ENet-CSharp#22]
Hi,
Is the library able to reconnect when disconnected?
I couldn't find this option.

**Comment by SoftwareGuy** [comment]
Unfortunately not. ENet doesn't do automatic re-connections, however if it does detect some minor weirdness with the connection it will attempt to keep the connection alive. But if it disconnects or times out, the game is over. 

Re-connection is not a difficult thing to handle in the high-level design of your game/application.

**Comment by SoftwareGuy** [comment]
No response. Closing for now.
