### ISSUE TITLE
Client connection timeout

### ISSUE THREAD

**Issue by valkyrienyanko** [SoftwareGuy/ENet-CSharp#26]
## Issue
I am trying to connect Unity ENet-CSharp client to ENet-CSharp dotnet server. The problem is the client always times out when trying to connect to the server. "Client connection timeout" is logged to the console.

## Steps to Reproduce
1. Download my [Unity client](https://github.com/Kittens-Rise-Up/client) and open up project up through Unity Hub
2. Setup a simple dotnet console app with default enet-csharp server code
3. Run server
4. Run client

## Code
Client Code: https://github.com/Kittens-Rise-Up/client/blob/main/Assets/Scripts/ENetClient.cs

Server code is default template provided from the `README.md` from this repo `SoftwareGuy/ENet-CSharp`

## Notes
My windows firewall is disabled.

Ports are the same on client and server.

I used Nuget to get ENet-CSharp for the dotnet server and I compiled ENet-CSharp from source (inside MSBuild folder) and placed `ENet-CSharp.dll` and `enet.dll` (found from `MSBuild\ENetCSharp\bin\Debug\netstandard2.0`) inside the Unity client. Maybe I am using 2 different versions of enet and that's why the client cannot connect to the server?

I have tried using my IPv4, my external IP and "127.0.0.1", all of them result in a client timeout.

I'm not sure why this is happening as I remember having no issues with this setup in the past.

## Update
I was able to connect a dotnet client to a dotnet server with no issues even with my firewall enabled. However connecting the Unity client to the dotnet server does not work.

**Comment by valkyrienyanko** [comment]
I solved this by including the source of enet-csharp (ENet.cs) directly into the Unity project along with the enet.dll I got from compiling the source (from the msbuild folder). However it would be nice to know why the ENet-CSharp.dll did not work in place of the ENet.cs.

**Comment by valkyrienyanko** [comment]
Now I'm having the same problems again seconds after I thought I solved it? I saw it working in front of my eyes one time.

**Comment by SoftwareGuy** [comment]
Hey there. 👋 

You're on the right track, but what's happening is you're literally just telling ENet to check for one event, then dispose and clean up. You need to put the logic in your FixedUpdate in a while loop, but don't do that in a FixedUpdate. That will hang Unity's main thread and cause your game to freeze when stuff is happening on the network.

An example of a threaded implementation is in my [Ignorance Client](https://github.com/SoftwareGuy/Ignorance/blob/master/Assets/Mirror/Runtime/Transport/Ignorance/Core/IgnoranceClient.cs) code that I use for Ignorance. It is not difficult - you just use two ConcurrentQueue for Incoming and Outgoing events, let ENet poll and feed the queues, then your main logic just empties the queue every loop.

The only thing by using threads is that you need to ensure you follow thread-safety. Accessing things across threads can cause Access Violations, which will instantly crash your game. When working with a thread, it has its own bubble. ConcurrentQueues are thread safe, so you can give stuff into the thread bubble and get things from the thread bubble without interrupting ENet.

If you are stumped on how to use ConcurrentQueues and whatnot, I can probably supply a code sample that can be adapted from - the ENet-CSharp example code shows a example non-threaded implementation.

**Comment by valkyrienyanko** [comment]
Thank you for the detailed reply! I've been tearing myself apart all day today trying to figure out why this was not working. I've heard of threads before but never used them extensively enough to gain any real solid experience with them. I'll be looking into thread safety for the next few days. My end goal is to eventually implement a UDP ENet model for C# and C++.
