### ISSUE TITLE
LAN Peer Discovery

### ISSUE THREAD

**Issue by AndrewIGD** [SoftwareGuy/ENet-CSharp#27]
Hello, I've managed to implement game hosting and joining in Unity and it works great!

An issue I currently have is the method one should use to connect to a host. Currently, the user has to type the IP and then connect, which is not exactly ideal as the game is meant to run on Android phones that support Google Cardboard. 

One method I found is by using `Address.SetHost("255.255.255.255")` which works fine, but I would like to be able to find multiple hosts on a single LAN Network and then choose which one I would like to connect to. How would something like this be done?

**Comment by SoftwareGuy** [comment]
This is a tricky one - ENet's broadcast address function was more intended for a single ENet server instance in the network. I can see your usage case though.

Is the server on a PC or is the server designed to be running on another Android Cardboard device?

**Comment by SoftwareGuy** [comment]
No response - closing for now.
