### ISSUE TITLE
Having Troubles Understanding the Parameters for Peer.Timeout(...)

### ISSUE THREAD

**Issue by valkyrienyanko** [SoftwareGuy/ENet-CSharp#30]
## My Question
What is the difference between `timeoutLimit`, `timeoutMinimum` and `timeoutMaximum`?

I put the defenition below for reference.

## Peer.Timeout(uint timeoutLimit, uint timeoutMinimum, uint timeoutMaximum)
`Peer.Timeout(uint timeoutLimit, uint timeoutMinimum, uint timeoutMaximum)` sets a timeout parameters for a peer. The timeout parameters control how and when a peer will timeout from a failure to acknowledge reliable traffic. Timeout values used in the semi-linear mechanism, where if a reliable packet is not acknowledged within an average round-trip time plus a variance tolerance until timeout reaches a set limit. If the timeout is thus at this limit and reliable packets have been sent but not acknowledged within a certain minimum time period, the peer will be disconnected. Alternatively, if reliable packets have been sent but not acknowledged for a certain maximum time period, the peer will be disconnected regardless of the current timeout limit value.

**Comment by rybakatchya** [comment]
From looking at the code it appears it is as follows.

Timeout(32, 5000, 30000);

if a reliable packet is not acknowledged within an average round-trip time plus a variance tolerance until timeout reaches a set limit(32).   If the timeout is thus at this limit(32) and reliable packets have been sent but not acknowledged within a certain minimum time period(5000), the peer will be disconnected. Alternatively, if reliable packets have been sent but not acknowledged for a certain maximum time period(30000), the peer will be disconnected regardless of the current timeout limit value(32).

**Comment by valkyrienyanko** [comment]
I'm still as confused as I was before.

**Comment by rybakatchya** [comment]
Ok say you set peer.Timeout(32, 5000, 30000). I believe this means that if you send out a reliable packet and that peer doesn't respond with an acknowledge message (all enet peers acknowledge they received reliable packets internally) 32 times before receiving an acknowledge message a clock starts, after 5000 milliseconds have passed on the clock if the peer still has not acknowledged receiving the reliable packets, they are timed out. Now regardless of what is stated above if 30,000 milliseconds pass without the peer acknowledging reliable packets they are timed out weather they have hit the 32 limit or not yet. 

I could be wrong its kind of hard to figure out in the code, but from what I see going on in the code and what the description is that is the best guess I can put together.

**Comment by valkyrienyanko** [comment]
Still very confusing, but this isn't really an issue for me so closing this now.
