### ISSUE TITLE
ENet.Packet.Create(IntPtr,...) not accepting IntPtr.Zero

### ISSUE THREAD

**Issue by Pixinger** [SoftwareGuy/ENet-CSharp#32]
I was just reading through the code and maybe found one inconsistency.

The Managed wrapper of ENet.Packet.Create(IntPtr, ...) is not accepting a IntPtr.Zero as a first parameter. It will throw an exception.

```csharp
public void Create(IntPtr data, int length, PacketFlags flags)
{
  // I would suggest to remove this exception.
  if (data == IntPtr.Zero)
    throw new ArgumentNullException("data");

  // This check seems to be still important.
  if (length < 0)
    throw new ArgumentOutOfRangeException("length");
  nativePacket = Native.enet_packet_create(data, (IntPtr)length, flags);
}
```

When comparing the native interface, IntPtr.Zero looks like a valid option. According to my understanding, it will simply reserve the requested memory, WITHOUT actually copy provided data. This way the user could manually write to the buffer, by requesting:
```csharp
var myPointer = ENet.Packet.Data;
// Possibly use code like this to write to the buffer.
System.Runtime.InteropServices.Marshal.WriteInt32(myPointer, 0, 4);
// Or use unsafe code like:
int* pBuffer = (int*)myPointer.ToPointer();
*pBuffer = 11;
```
I am using this approach to 'serialize' a structure directly to the network buffer. This way, I do not have to serialize the data into a byte array, before copy it a second time to the native buffer. That should prevent unneccessary allocations.

Here is the relevant native code:

```c++
ENetPacket* enet_packet_create(const void* data, size_t dataLength, uint32_t flags) 
{
  ENetPacket* packet;
  
  if (flags & ENET_PACKET_FLAG_NO_ALLOCATE) {
	  packet = (ENetPacket*)enet_malloc(sizeof(ENetPacket));
  
	  if (packet == NULL)
		  return NULL;
  
	  packet->data = (uint8_t*)data;
  } else {
	  packet = (ENetPacket*)enet_malloc(sizeof(ENetPacket) + dataLength);
  
	  if (packet == NULL)
		  return NULL;
  
	  packet->data = (uint8_t*)packet + sizeof(ENetPacket);
  
          // ***********************
          // This is the relevant part:
          // "data" NULL is valid, it will only prevent a copy operation. It look like this is an intended feature.
          // ***********************
	  if (data != NULL) 
		  memcpy(packet->data, data, dataLength);
  }
    
  packet->referenceCount = 0;
  packet->flags = flags;
  packet->dataLength = dataLength;
  packet->freeCallback = NULL;
  packet->userData = NULL;

  return packet;
}
```

What do you think about it, or did I miss something relevant?

Kind regards 
Pix

**Comment by SoftwareGuy** [comment]
Hmm, that’s an interesting finding you have here. 🤔

I could remove the IntPtr.Zero check which would allow us to do the advanced trickery that you mention, although the exception being thrown in the first place probably is to prevent unknown or undefined behaviour by a developer oversight. 

If it works for you and you use it in a high traffic situation without any memory access violations, then I think it will benefit others that want to do memory manipulation for more control over their data access.

Did you want to PR it? I’ll probably test to ensure it doesn’t break and then merge it in. 😃

**Comment by Pixinger** [comment]
Hey, sorry for responding so late. There where... some things to do...

I guess removing the IntPtr.Zero check could lead to issues for other developers - which currently may rely on this feature. 
What about adding a new method, that makes the behaviour obvious. Maybe something like this:

```csharp
public void Create(int length, PacketFlags flags)
{
  if (length < 0 || length > data.Length)
    throw new ArgumentOutOfRangeException("length");
  
  nativePacket = Native.enet_packet_create(IntPtr.Zero, (IntPtr)length, flags);
}
```

Removing the byte[] argument makes it quite visible, that there cant be any copy operation. Specifying the length on the other hand, makes it clear, that there is some memory reserved.

Regarding the stability question: I am not done with testing. So if you need my answer to that, we have to wait a little until testing is complete ;-)

**Comment by SoftwareGuy** [comment]
Having a Create with a different overload would work, I guess. Did you get any further with your testing?

**Comment by SoftwareGuy** [comment]
Closing due to age of tissue.
