### ISSUE TITLE
Problems when sending reliable packets on high frequency

### ISSUE THREAD

**Issue by japajoe** [SoftwareGuy/ENet-CSharp#33]
First I want to say thanks for this amazing library. I really enjoy using it but I'd like to share my findings and possibly get a confirmation from your end. I've started using the ENet-CSharp implementation from nxrighthere, and made my own library on top of it. I noticed that after some (random) amount of time the server would stop receiving packets from one or more clients. I initially thought I created a bug somewhere, and since my library was pretty wild and I found it hard to track down the issue, I decided to create a new one. So far so good, I had everything laid out nicely and it was much easier to use and maintain. 

Then I noticed I got the same problem as I had before. After some random amount of time the server stopped receiving packets from one or more clients. The server would still see these clients as connected, and it happily kept sending packets (with old data) to everyone including the client who could not get his packets delivered anymore. These 'zombie' clients also kept receiving packets, they were just unable to get their packets delivered to the server. I've done a lot of logging to find the issue but I just could not find any logical explanation to the cause. I considered that maybe there's a bug in nxrigthere's library, so I tried yours with good hope it might not have this problem. Turned out I was wrong. I had the same problem and I started to realize it possibly isn't a bug, but just something I'm not fully understanding.

Long story short, I was thinking about the numbers of sent/received packets on the clients, and made the observation that the number of sent packets was consistently higher than the number of received. I then thought maybe it has something to do with the fact that I am sending reliable packets on a high frequency and on failure of delivery, they have to be resent, which possibly could cause a backlog of packets until everything crumbles. So I tested to mark these packets as unreliable, and behold, the issue seemed to be gone. The number of sent packets is now also consistently lower than the number of received. I realize now what I did was probably not the smartest thing to do, but I didn't expect it to be so problematic.

My question for you: do you think sending reliable packets on a high frequency (lets say 10 packets per second) could lead to the issue I described? If not, why not and how else should one deal with this? If yes, are you willing to add this issue to the 'common mistakes during integration'? I have done a lot of digging but couldn't find any specific information regarding all this, and it might be useful for others to consider.

**Comment by SoftwareGuy** [comment]
Hmm… this is an interesting scenario.

Surely 10 packets per second (per peer?) isn’t going to push ENet over the edge. It is true that ENet will resend “lost” packets if it feels a client is not responding and replying with ACKs, in which it will resend until it gives up and times out. If you are pushing a huge amount of packets though, then yes, ENet queues may be getting full and it’s suffering under the load.

My first question would be what are your clients? Are they devices running on desktops or are they mobile? My initial retort would be that if it’s mobile then you’re prone to all sorts of random things happening since UDP on mobile can be a pain in the ass, but you say that the clients remain connected but disconnected in a zombie state. I’ve seen this once or twice but haven’t seen it recently.

You did say that switching from Reliable to Unreliable helps. That probably sounds about right because the packet tracking overhead is reduced. I’ll see if my friend has any two cents that he might know.

**Comment by SoftwareGuy** [comment]
Alright, I did some talking to my contact and they said that they had lots more packets in flight without any issues on reliable. It might be a implementation matter. Could you share the implementation (even if it's gutted but the problematic part is kept intact), or do a secret gist with an outline of the code you use plus the actual enqueue stuff so we can dig deeper?

**Comment by japajoe** [comment]
I have to scratch everything I said about reliable packets because now I'm experiencing the same with unreliable. It's so unpredictable that it's difficult for me to tell what is going on. Yesterday I've tested for 3 hours and all seemed fine. Could it possibly be that I'm sending packets from the main (Unity) thread while the connection is on a different thread? Should I put the outgoing packets into a concurrent queue so I can send them off from the networking thread? The incoming packets do go in a concurrent queue which I then dequeue on the main thread. I'm developing for PC (Linux/Windows/MacOS).

Edit: I've gone ahead and created a 'SendQueued' method which takes a packet and copies the payload to a buffer which I get from an ArrayPool so I can safely add the data to a concurrent queue. The network thread processes this queue when there's data in it, and so far everything seems to be still working but I've yet to see if this is the solution. I'd like to hear your opinion whether this could be a flaw in my design since you've mentioned something about enqueueing things (which I did not do for outgoing packets from the client). The server does everything on a single thread so that should be fine.

**Comment by SoftwareGuy** [comment]
My implementation that I use for Ignorance which handles lots of packets comfortably inside the Unity environment (although it is hooked up to Mirror, but the core is detachable) is mainly this:

- Main thread handles Connection Events (Connect, Disconnect) and populates packet items into the Outgoing ConcurrentQueue when it needs to send things to the server or clients.
- Main thread TryDequeues from the Incoming ConcurrentQueue that is being populated from the ENet network loop thread.
- ENet network loop thread is responsible for keeping ENet fed and happy. It polls for events, TryDequeues the Outgoing queue and also populates the Connection Events and Incoming queues.
- Keeping network stuff to a seperate thread may be a headache but ENet likes being able to run as fast as it can. It doesn't like to be choking if your application is super bogged down.

Ignorance [can be found here](https://github.com/SoftwareGuy/Ignorance) in my repositories; the stuff of interest would be Ignorance Standalone which is attached to the transport layer. You're welcome to use that as a reference to see if that would help solve the issue.

Your implementation sounds like it's similar to mine. I'm currently away from my office so I can't sit down and try to piece your implementation together in my head right at this point in time.

**Comment by japajoe** [comment]
It is very similar indeed and after having 'fixed' the outgoing packets by using a queue I'm still waiting for the bug to happen again. It was the only place where I blatantly violated cross threading principles. It's been many hours so I stopped counting them and carefully coming to the conclusion that this was the big problem after all. The unpredictable nature made it very hard to track down but the hint you gave about queues was very valuable. I had no clue about this because I had not seen any proper examples about using ENet in a cross thread context.  If it happens that I walk into this problem again I'll let you know, for now I feel confident to say the problem is gone and it certainly was a bug on my end. Thanks for your time and insight!

**Comment by SoftwareGuy** [comment]
Going to close this - if you're still experiencing it by all means please re-open :smile:
