### ISSUE TITLE
Does this support the unity engine?

### ISSUE THREAD

**Issue by scc172fly** [SoftwareGuy/ENet-CSharp#34]
Can I support Unity? I don't see a release version of Android available.

**Comment by SoftwareGuy** [comment]
Yes, ENet-CSharp supports Unity... well, any C# environment that can do NET Standard 2.0 at least.

ENet is compatible with Android. You'll need the Android NDK Tools yourself to compile. I should really make an Android build script that you can run after you've installed the tools.
