### ISSUE TITLE
Can you provide the x86 version of the pre-built library? 

### ISSUE THREAD

**Issue by pedoc** [SoftwareGuy/ENet-CSharp#35]
Due to some legacy reasons, our program has to run on x86, but the pre-built library does not include the x86 version. Is it possible to provide them? 

Of course, on windows I can use cmake to generate x86 and x64 configurations to solve this problem, but we still need to support linux at least, but I am not an expert in this area, if any help information is available, it would be greatly appreciated.

thanks

**Comment by SoftwareGuy** [comment]
So, you're saying you need 32bit and 64bit Windows and Linux libraries?

I could probably make a set of build scripts that automate the whole process, and I guess it wouldn't be too much of a hassle to hook it into the GitHub Actions pipeline to make 32bit binaries. They'd just be unsupported.

**Comment by pedoc** [comment]
yep，win+linux.

I made some attempts and finally successfully built a 32-bit library on Fedora.
I can share information:

install Fedora 34（vmware)，Can not succeed on centos7.

```
sudo yum install g++
sudo yum install libstdc++-devel.i686 
sudo yum install glibc-devel.i686

git clone ENet-CSharp
cd ENet-CSharp

//build x64
g++ enet.c -fPIC -shared -o libenet.so

//build x86
g++ enet.c -fPIC -shared -o libenet.x86.so -m32
```

If you can add this to the default support, that would be great.
please close this issue if needed.

thanks again :)

**Comment by SoftwareGuy** [comment]
I'll spin up a virtual machine and give this a shot sometime soon.

**Comment by SoftwareGuy** [comment]
Will add build scripts for Linux x86 within the near future, going to close for now.
