### ISSUE TITLE
Do you only call ENet.Library.Initialize() once?

### ISSUE THREAD

**Issue by valkyrienyanko** [SoftwareGuy/ENet-CSharp#38]
I have setup a game where the client and server are shipped together.

## What I'm doing right now
I call `ENet.Library.Initialize();` and `ENet.Library.Deinitialize();` for each client and server I create.

In my game there are sometimes more than one client (dummy clients) that are created and call `ENet.Library.Initialize();` for each dummy client. And finally call `ENet.Library.Deinitialize();`

I know for sure that a game can have a client and server running at the same time meaning `ENet.Library.Initialize();` gets called twice before `ENet.Library.Deinitialize();` gets called.

## Should I be doing this instead?
Should I only initialize and deinitialize ENet once in some static class? Init on game startup, deinit on game exit.

Just asking because maybe there is some weird thread design rule I need to follow? Sorry if this is a dumb question.

**Comment by SoftwareGuy** [comment]
I personally do the Library initialization and de-initialization inside a thread, which from what I understand means that it's initialized only for that thread. I would assume that attempting to use ENet in a thread outside of the thread I initialize it in would cause all sorts of weirdness, but I am not sure what scope the initialization is - if it's global (as in, initialize it and it's ready to go globally) or local-only (i.e only the thread that initialized it).

**Comment by valkyrienyanko** [comment]
I switched over to initializing ENet once on startup across all threads and deinitialized it once on game exit and everything seems to work just fine.
