### ISSUE TITLE
Does enet merge small packets before sending?

### ISSUE THREAD

**Issue by rybakatchya** [SoftwareGuy/ENet-CSharp#39]
If I send 100 packets in a single frame is enet going to then send 100 packets over the wire or does it combine packets and send only sometimes? I am using service with the timeout set to 0 btw.

**Comment by SoftwareGuy** [comment]
According to the documentation, if you're not using the Instant flag, it should bundle the packet with others. This is the documentation for that Instant flag:

> PacketFlags.Instant a packet will not be bundled with other packets at a next service iteration and sent instantly instead. This delivery type trades multiplexing efficiency in favor of latency. The same packet can't be used for multiple Peer.Send() calls.

I am not 100% sure but one way to find out would be to check Wireshark or something similar to see how many packets get sent when you fire off 100 packets in a single frame. If that number of packets actually transmitted out over the wire is less than 100, then you'd know ENet is batching/bundling them.

Off the top of my head, it would bundle/combine them unless that packet flag was set.

**Comment by rybakatchya** [comment]
Alright yeah from looking at the enet website it does mention aggregation. Thank you.

Is there a suggested memory allocator to be used with enet? I haven't been able to find one for c# just native libraries.
