### ISSUE TITLE
Release for x86 platform

### ISSUE THREAD

**Issue by IgorManowar** [SoftwareGuy/ENet-CSharp#42]
Hello, friend! Thanks a lot for your great work. I want to use it in my project, But I need your help here.
My project has to have x86 architecture but x64 version provided here only. And the package from nuget seems to x64 also. 
I've tried to build x86 myself but I've managed to produce enet.dll and enet.lib and no I idea what to do next. I mean how to use it in my C# project. I've tried to added enet.dll through Reference in my project I got the error: 'enet.dll could not be added. Please make sure that the file is accessible, and that it is a valid assembly or COM component."
Will you be so kind to overcome the situation? Thanks a lot in advance.

I've managed to produce ENet-CSharp.dll. The projects compiles but when run  I got "Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified." What can be the reason? Thanks in advance.

**Comment by SoftwareGuy** [comment]
Don't add enet.dll as a reference in your project. It will be used by the ENet.cs wrapper. Simply ship it next to your binary (I think you can tell VS to copy it as a file to the project output directory).

I personally have not used ENet-CSharp as a DLL module - I would recommend including the `ENet.cs` file in your project as part of the projects' code. That is the intended usage case.

**Comment by IgorManowar** [comment]
Thanks. So then I will need to copy x86 enet.dll to the output directory only. Right?

**Comment by SoftwareGuy** [comment]
Yes. 😄

**Comment by IgorManowar** [comment]
Thank you, friend! I will try your approach. Please let me ask you for another help if something will go wrong.

**Comment by SoftwareGuy** [comment]
Closing this, feel free to reopen if there's any other issues.
