### ISSUE TITLE
Issues with C++ 

### ISSUE THREAD

**Issue by VENTDEV** [SoftwareGuy/ENet-CSharp#44]
Greetings! 

I'm using the latest release of this repo in a C++ server and C# client, 

With the C++ server, I'm including your enet.h file and I link your built libraries. (So no mix and matching versions.)

There is no address.host and enet_address_set_host() in the enet.h. You've said in several other threads that there is, but literally, there is no binding for it in your ENet.cs file or mention of it in enet.h. If you even search this repo here on github, you get a "We couldn't find any code matching 'enet_address_set_host' in SoftwareGuy/ENet-CSharp.

It would be nice to know a work around for this, since the official ENet tutorials and just about everything else on the net references:

```
ENetAddress address;
address.host = ENET_HOST_ANY; 
 enet_address_set_host(&address, "192.168.0.100"); 
```

If you try that with your header, you get address.host not found, ENET_HOST_ANY is ipv6 only? and enet_address_set_host not found. 

If I look back at the repo from 2019, it's there. But it isn't in the most current ones.

-----

As a work around, I do a enet_address_set_ip() or a enet_address_set_hostname(). But if you give these functions a ipv4 address, it only spits out an ipv6 of ffff0000...

**Comment by VENTDEV** [comment]
A little more info, was removed from your repo April 7th 2020, and from nxrightthere's on Sep 3rd. The lack of the function makes little difference to me, I just need to know the way to set up addresses using your C header.

**Comment by VENTDEV** [comment]
I ended up building the ipv4 struct myself, and that at least sets the server to assign itself the correct IP and ports. Still can't connect from the C# client, however. But progress... I think.

**Comment by VENTDEV** [comment]
I got it to work. 

Wisdom of ancients:
Convert your ip to an in_addr and assign it to the address.ipv4. You can then use enet_address_set_hostname to do the rest. 

All the other issues I had were related to VirtualBox and a forgotten firewall feature in Mageia. Oh well. :)

Thanks again, and sorry for the spam.

**Comment by SoftwareGuy** [comment]
All good, I'm glad you found a solution and shared it with the rest of us. 😄 👍
