### ISSUE TITLE
How to tell if client was disconnected because they exceeded max peers set on server?

### ISSUE THREAD

**Issue by valkyrienyanko** [SoftwareGuy/ENet-CSharp#45]
If I create a server with a max of 5 peers.

```cs
var maxPeers = 5;
server.Create(new Address { Port = port }, maxPeers);
```

And 6 peers try to join. The 5 peers will get in but the 6th peer will timeout. How can I inform the 6th peer that they could not enter the server because they exceeded the maximum peer limit instead of just saying "Your connection to the server timed out" implying that the server could be offline.

**Comment by SoftwareGuy** [comment]
You'd have to modify the ENet Native C library code for this. Looking at the handler for connects - [enet.h, line 1754](https://github.com/SoftwareGuy/ENet-CSharp/blob/c562654cfbb024eaad96ce878310dadaa652a1c7/Source/Native/enet.h#L1754) - it seems that if you connect and the peer list is full, you just time out. There's a few checks for different conditions too but it seems the general consensus is "Shit's full, not replying to you". There is no "server full" notification.

I probably would recommend using some debug log calls so they get emitted to the log file, so you can see what exactly the condition that's causing the connecting client to be ignored. I have an hunch it's something in the for loop at line 1766.

**Comment by valkyrienyanko** [comment]
ah nvm then. I guess if I want this kind of functionality with the existing enet implementation then I have 2 options

Option A) Emit the server player count / player joins / leaves to a web server. Whenever a client tries to join, check the web server

Option B) Leave the enet max peer count to some absurd high number like 999. If a client joins but exceeds say the 20 player limit then instantly disconnect them along with a byte that says that we kicked you because you exceeded this 20 player limit.
