### ISSUE TITLE
Is it normal to have a ~1 second delay between each client connection to the server?

### ISSUE THREAD

**Issue by valkyrienyanko** [SoftwareGuy/ENet-CSharp#46]
https://user-images.githubusercontent.com/6277739/227401995-36a698ef-051e-4311-8848-5967f4448c4d.mp4  

Above you can see it takes about 50 seconds for 50 clients to connect. During this time all the position packets are not sent because the connections are freezing up the server.

The delay between client connections is undesired, it would be nice if they all connected at the same time. I'm assuming these connection delays freeze up the server which would cause unwanted lag spikes in gameplay when someone joins the server.

Is there anyway to fix this? Am I doing something wrong?

Source can be found here: https://github.com/Valks-Games/Multiplayer-Template

**Comment by valkyrienyanko** [comment]
For fun I tested this with LiteNetLib as well and same thing happened.

After a bit of digging I've come across this https://stackoverflow.com/questions/6637932/why-sometimes-task-is-significantly-slower-than-thread

Doing this `ThreadPool.SetMinThreads(100, 100);` fixed everything.

So it was never a problem with enet, but rather the fact that tasks are enqueued to a pool and only 11 tasks execute at a time by default.

**Comment by SoftwareGuy** [comment]
I was going to also add that if you’re using a hostname instead of an IP there could be a delay as the native library does some lookup of the hostname for an IP address.

That is very interesting regarding ThreadPool.
